---
    name: Checks
    
    on: [push]
    
    jobs:
      test-lint:
        name: Test and Lint
        runs-on: ubuntu-20.04
        steps:
          - name: Login to Docker Hub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKERHUB_USER }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
              
          - name: Checkout
            uses: actions/checkout@v2
            
          - name: Install Latest Docker Compose
            run: |
              mkdir -p ~/.docker/cli-plugins/
              curl -SL https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
              chmod +x ~/.docker/cli-plugins/docker-compose
              
          - name: Test
            run: docker-compose run --rm app sh -c "python manage.py test"
            
          - name: Lint
            run: docker-compose run --rm app sh -c "flake8"
    